### ISSUE TITLE
some QC page images not rendering

### ISSUE THREAD

**Issue by navonacalarco** [TIGRLab/datman#56] opened 2016-08-11 18:50 UTC
Whenever you have time (no rush at all), try to figure out why some some QC pages don't successfully generate a scan image, though the scan is in XNAT and our file system (and can be opened in MRIcron, etc).

Example: /archive/data-2.0/PRELAPSE/qc/PRE05_CRY_11015_01/qc_PRE05_CRY_11015_01.html

**Comment by josephdviviano** [comment] 2016-08-11 18:54
NIFTI CRY
I smile.

**Comment by josephdviviano** [comment] 2016-08-11 18:55
@edickie what do the logs say for this run of the QC pipeline? It's just the T2 image that is corrupted.

**Comment by navonacalarco** [comment] 2016-08-11 19:00
U CRI i nii

**Comment by DESm1th** [comment] 2016-08-11 19:09
The problem is between slicer and those specific T2 niftis. It consistently produces broken images from them. I don't know much about slicer, what would cause that?

**Comment by josephdviviano** [comment] 2016-08-11 19:10
If you try to run slicer on the file, what error does it produce?

**Comment by DESm1th** [comment] 2016-08-11 19:14
It doesn't produce any error at all, it just spits out a broken image. But running the exact same command with a different T2 nifti from the project (e.g. /PRE01_SFD_32002_01_01_T2_09_Sag-CUBE-T2-256x256x25.6x1.0.nii.gz ) works just fine

**Comment by josephdviviano** [comment] 2016-08-11 19:36
Well in that case, it's an FSL bug. Is this true with the most recent version of FSL loaded (or does slicer have a verbose command)?

**Comment by navonacalarco** [comment] 2016-08-11 19:38
Not sure how this factors in, but *I think* the issue appears for some sites (and if so, for all T2s for that site), but not others (for no T2s from that site).

**Comment by DESm1th** [comment] 2016-08-11 19:42
When I ran it I had FSL/5.0.9 loaded and slicer/4.5.0-20160714 . Not sure about a verbose command, I don't know anything about slicer and running "slicer --help" gives a segmentation fault, haha. I just copied the command qc-html.py runs to generate the images.

**Comment by josephdviviano** [comment] 2016-08-11 19:43
@DESm1th the 'slicer' command in question is an FSL command, you should be able to run with with `slicer/4.5.0-20160714` unloaded (maybe try it?)

**Comment by DESm1th** [comment] 2016-08-11 19:47
Oh! Yeah slicer still runs without the slicer module. Thanks for letting me know. Still throws a segmentation fault for "slicer --help" though, and still broken for that PRE05 T2

**Comment by josephdviviano** [comment] 2016-08-11 19:58
slicer is compiled C code from FSL -- we could complain to them but I don't see that helping too much.

Either we learn to live with this, figure out a work around (with no error message this is going to be pure trial and error), or we're going to have to replace slicer with another tool. I'm not married to slicer.

@edickie thoughts?

**Comment by josephdviviano** [comment] 2016-09-15 03:49
I'm closing this.

**Closed by josephdviviano** 2016-09-15 03:49 UTC
